#Download base image debian 9
FROM debian:9
MAINTAINER Ivan Gomez "ivangomezlapenya@gmail.com"

# Update debian9 Software repository

RUN apt-get update -yq \
  && apt-get upgrade -yq \
  && apt-get install curl gnupg -yq \
  && curl -sL https://deb.nodesource.com/setup_10.x | bash \
  && apt-get install nodejs -yq

WORKDIR /home
